name: sweetcorn-example

services:
  sweetcorn:
    build:
      context: ..
    ports:
      - "4317:4317"
      - "4318:4318"
      - "13579:13579"
    networks:
      - sweetcorn-net

  grafana:
    image: grafana/grafana:12.1.1
    restart: on-failure
    command:
      - --config=/etc/grafana-config/grafana.ini
    volumes:
      - ./grafana:/etc/grafana-config
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 1s
      timeout: 10s
      retries: 5
      start_period: 0s
      start_interval: 0s
    networks:
      - sweetcorn-net

  hotrod:
    image: jaegertracing/example-hotrod:1.72.0
    ports:
      - "8080:8080"
      - "8083:8083"
    command: ["all"]
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://sweetcorn:4318
    depends_on:
      - sweetcorn
    networks:
      - sweetcorn-net

networks:
  sweetcorn-net:
